site_name: Multitask learning
theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            show_root_heading: true
  - mkdocs-jupyter:
      include_requirejs: true
  - coverage:
      html_report_dir: docs/htmlcov

hooks:
  - docs/variational/hooks.py
  - docs/task_clustering/hooks.py
  - docs/sbmtl/hooks.py

nav:
  - Home: index.md
  - Variational: 
    - Introduction: variational/intro.md
    - API Reference: variational/reference.md
    - Simple example: variational/elementary.ipynb
  - Tusk clustering: 
    - Example: task_clustering/multi-task-learning.ipynb
  - Sparse multitask: 
    - Example: sbmtl/experiment_testing_method.ipynb
  - Coverage report: coverage.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js