site_name: My Docs
theme:
  name: material

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      include_requirejs: true

hooks:
  - docs/variational/hooks.py
  - docs/task_clustering/hooks.py
  - docs/sbmtl/hooks.py

nav:
  - Home: index.md
  - Variational: 
    - Introduction: variational/intro.md
    - API Reference: variational/reference.md
    - Simple example: variational/elementary.ipynb
  - Tusk clustering: 
    - Example: task_clustering/multi-task-learning.ipynb
  - Sparse multitask: 
    - Example: sbmtl/experiment_testing_method.ipynb

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js