[tool.poetry]
name = "bmm_multitask_learning"
version = "0.1.0"
description = "algos for multitask learning"
authors = ["sem-k32 <kirill.semkin32@mail.ru>"]
readme = "README.md"
include = [
    { path = "bmm_multitask_learning" }
]


[tool.poetry.dependencies]
python = "^3.12"
torch = "^2.6.0"
numpy = "^2.2.3"
pandas = "^2.2.3"
omegaconf = "^2.3.0"
pipe = "^2.2"
lightning = "^2.5.0.post0"
pytest = "^8.3.5"
sphinx = "^8.2.3"
pyro-ppl = "^1.9.1"
torchmetrics = "^1.7.0"
plotly = "^6.0.1"
nbconvert = "^7.16.6"


[tool.poetry.group.dev.dependencies]
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
