name: pages

on:
  workflow_run:
    workflows: ["tests"]
    types: [completed]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache 
          restore-keys: |
            mkdocs-material-
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          virtualenvs-path: .venv
          installer-parallel: true
      - run: poetry install --only doc --no-interaction
      - name: Download coverage artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage-report
          path: coverage/
      - run: mv coverage/htmlcov/ docs/
      - run: poetry run mkdocs build
      - run: poetry run mkdocs gh-deploy --force